version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
